# exporter.py
# Export research results to Markdown or PDF formats.

import io
import textwrap
from datetime import datetime


# ─────────────────────────────────────────────────────────────
# MARKDOWN EXPORT
# ─────────────────────────────────────────────────────────────

def export_markdown(result, followups=None):
    """
    Generate a Markdown report from a research result dict.
    Returns a UTF-8 string.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = []

    lines.append(f"# AIRA AI Research Report")
    lines.append(f"")
    lines.append(f"**Question:** {result.get('query', '')}")
    lines.append(f"")
    lines.append(f"**Mode:** {result.get('mode', 'normal').capitalize()}  ")
    lines.append(f"**Research Time:** {result.get('time', 0):.1f}s  ")
    lines.append(f"**Generated:** {now}  ")
    lines.append(f"**Sources Found:** {result.get('total_sources', 0)}  ")
    lines.append(f"**Passages Analysed:** {result.get('total_passages', 0)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Summary
    lines.append("## Answer")
    lines.append("")
    summary = result.get("summary", "").strip()
    lines.append(summary if summary else "_No summary available._")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Sources
    sources = result.get("sources", [])
    if sources:
        lines.append("## Sources")
        lines.append("")
        for i, s in enumerate(sources, 1):
            title = s.get("title") or s.get("domain") or s.get("url", "")
            url = s.get("url", "")
            score = s.get("score", 0)
            lines.append(f"{i}. **[{title}]({url})**  ")
            lines.append(f"   Domain: `{s.get('domain', '')}` | Relevance: {score:.2%}")
            lines.append("")

    lines.append("---")
    lines.append("")

    # Relevant Passages
    passages = result.get("passages", [])
    if passages:
        lines.append("## Relevant Passages")
        lines.append("")
        for p in passages:
            domain = p.get("url", "").replace("https://", "").replace("http://", "").split("/")[0]
            lines.append(f"### {domain}")
            lines.append(f"**Relevance:** {p.get('score', 0):.2%}  ")
            lines.append(f"**Source:** <{p.get('url', '')}>")
            lines.append("")
            lines.append(f"> {p.get('passage', '')}")
            lines.append("")

    # Follow-ups
    if followups:
        lines.append("---")
        lines.append("")
        lines.append("## Follow-up Questions")
        lines.append("")
        for fu in followups:
            lines.append(f"### Q: {fu.get('question', '')}")
            answer = fu.get("answer", {})
            lines.append("")
            lines.append(answer.get("summary", "_No answer available._"))
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("_Report generated by AIRA AI Research Assistant_")

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────
# SAFE TEXT HELPER
# ─────────────────────────────────────────────────────────────

def _safe(text: str) -> str:
    """
    Sanitize a string for fpdf2's latin-1 (cp1252) encoder.
    Normalises unicode quotes/dashes to ASCII, then encodes with 'replace'
    to drop any remaining non-encodable characters — prevents crashes on
    text scraped from websites that contains smart quotes, emoji, etc.
    """
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
        "\u2013": "-", "\u2014": "-", "\u2026": "...", "\u00a0": " ",
        "\u2022": "*", "\u2192": "->", "\u2190": "<-", "\u00b7": "-",
        "\u00e2\u0080\u0099": "'",  # mojibake
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="replace").decode("latin-1")


# ─────────────────────────────────────────────────────────────
# PDF EXPORT
# ─────────────────────────────────────────────────────────────

def export_pdf(result, followups=None):
    """
    Generate a PDF report. Returns raw bytes.
    Requires: fpdf2  (pip install fpdf2)
    """
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError("fpdf2 is required: pip install fpdf2")

    class _SafePDF(FPDF):
        def multi_cell(self, *args, **kwargs):
            kwargs.setdefault("new_x", "LMARGIN")
            kwargs.setdefault("new_y", "NEXT")
            return super().multi_cell(*args, **kwargs)

    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    pdf = _SafePDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # ── Title ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(30, 30, 60)
    pdf.multi_cell(0, 12, "AIRA AI Research Report", align="C")
    pdf.ln(4)

    # ── Metadata ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(
        0, 6,
        f"Generated: {now}  |  Mode: {result.get('mode','normal').capitalize()}  "
        f"|  Time: {result.get('time',0):.1f}s  "
        f"|  Sources: {result.get('total_sources',0)}",
        align="C",
    )
    pdf.ln(6)

    # ── Separator ─────────────────────────────────────────────
    pdf.set_draw_color(180, 180, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(6)

    # ── Question ──────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(40, 40, 80)
    pdf.multi_cell(0, 8, "Research Question", align="L")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(20, 20, 40)
    pdf.multi_cell(0, 7, _safe(result.get("query", "")), align="L")
    pdf.ln(6)

    # ── Summary ───────────────────────────────────────────────
    _pdf_section(pdf, "Answer", _safe(result.get("summary", "No summary available.")))

    # ── Sources ───────────────────────────────────────────────
    sources = result.get("sources", [])
    if sources:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(40, 40, 80)
        pdf.multi_cell(0, 8, "Sources", align="L")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(20, 20, 40)
        for i, s in enumerate(sources, 1):
            title = _safe(s.get("title") or s.get("domain") or s.get("url", ""))
            score = s.get("score", 0)
            pdf.multi_cell(
                0, 6,
                f"{i}. {title} ({_safe(s.get('domain',''))}) - Relevance: {score:.0%}",
                align="L",
            )
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(0, 80, 180)
            pdf.multi_cell(0, 5, _safe(s.get("url", "")), align="L")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(20, 20, 40)
            pdf.ln(2)
        pdf.ln(4)

    # ── Passages ──────────────────────────────────────────────
    passages = result.get("passages", [])
    if passages:
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(40, 40, 80)
        pdf.multi_cell(0, 8, "Relevant Passages", align="L")
        pdf.ln(2)
        for p in passages:
            domain = _safe(
                p.get("url", "").replace("https://", "").replace("http://", "").split("/")[0]
            )
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(60, 60, 120)
            pdf.multi_cell(0, 6, f"{domain} - {p.get('score', 0):.0%} relevance", align="L")
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, _safe(p.get("url", "")), align="L")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 50)
            pdf.multi_cell(0, 6, _safe(p.get("passage", "")), align="L")
            pdf.ln(4)

    # ── Follow-ups ─────────────────────────────────────────────
    if followups:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(40, 40, 80)
        pdf.multi_cell(0, 8, "Follow-up Questions", align="L")
        pdf.ln(4)
        for fu in followups:
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 80, 150)
            pdf.multi_cell(0, 7, f"Q: {_safe(fu.get('question', ''))}", align="L")
            pdf.ln(1)
            answer = fu.get("answer", {})
            _pdf_section(pdf, "A", _safe(answer.get("summary", "No answer.")), title_size=10)

    # ── Footer ────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, "Generated by AIRA AI Research Assistant", align="C")

    return bytes(pdf.output())


def _pdf_section(pdf, title, body, title_size=13):
    pdf.set_font("Helvetica", "B", title_size)
    pdf.set_text_color(40, 40, 80)
    pdf.multi_cell(0, 8, title, align="L")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(20, 20, 40)
    pdf.multi_cell(0, 6, body, align="L")
    pdf.ln(6)
